(ns poker-client.player
  (:require [clojure.tools.logging :refer [info]]))

(defprotocol IPlayer
  (bot-name [_])
  (action-request [this request])
  (register-for-play-response [this event])
  (play-is-started-event [this event])
  (community-has-been-dealt-a-card-event [this event])
  (player-bet-big-blind-event [this event])
  (player-bet-small-blind-event [this event])
  (player-called-event [this event])
  (player-checked-event [this event])
  (player-folded-event [this event])
  (player-forced-folded-event [this event])
  (player-quit-event [this event])
  (player-raised-event [this event])
  (player-went-all-in-event [this event])
  (server-is-shutting-down-event [this event])
  (show-down-event [this event])
  (table-changed-state-event [this event])
  (table-is-done-event [this event])
  (you-have-been-dealt-a-card-event [this event])
  (you-won-amount-event [this event]))
